### ISSUE TITLE
LinkSheet not launching correctly from LinkSheetCompat

### ISSUE THREAD

**Issue by pressRtowin** [1fexd/LinkSheetCompat#2]
Not sure if this is a bug with LinkSheet or LinkSheetCompat, but when LinkSheetCompat is called on to handle a link, my whole screen dims as though some overlay was opened, but nothing else appears, and my entire screen becomes unresponsive to touch until I perform a navigation gesture (like going home or back).

Latest versions of all, including nightly LinkSheet.

Fold5

Android 14/One UI 6.0

**Comment by 1fexd** [comment]
Fixed via https://github.com/1fexd/LinkSheet/commit/83e2a1488ee24459a100ea364c1b7fa081357d63, thanks!
